#
# This file contains Nagios configuration for monitoring Bird router daemons
# (both Birdseye and Birdwatcher API types).
#
# WARNING: this file is automatically generated using the
#   api/v4/nagios/birdseye-daemons/{template}/{vlanid} API call to IXP Manager.
#
# Any local changes made to this script will be lost.
#
# See: https://docs.ixpmanager.org/latest/features/nagios/
#
<?php if( $t->vlanid ): ?>
# Limited to VLAN ID: <?= $t->vlanid ?>
<?php endif; ?>
#
# Generated: <?= now()->format( 'Y-m-d H:i:s' ) . "\n" ?>
#
#
# The following objects are used by inheritance here and need to be defined by your own configuration:
#
# 1. Host definition:    <?= $t->host_definition ?>;
# 2. Service definition: <?= $t->service_definition ?>.
#

<?php
    $hosts   = [];
    $hg_name = 'bird-daemons' . ( $t->vlanid ? ('-vlanid-' . $t->vlanid) : '' );
    /** @var \IXP\Models\Router $d */
    foreach( $t->routers as $d ):

        if( !$d->api ) {
            continue;
        }

        $hosts[] = "bird-{$d->handle}";
        $checkCmd = $d->api_type === \IXP\Models\Router::API_TYPE_BIRDWATCHER
            ? 'check_birdwatcher_daemon'
            : 'check_birdseye_daemon';
?>

define host {
    use                     <?= $t->host_definition . "\n" ?>
    host_name               bird-<?= $d->handle . "\n" ?>
    alias                   <?= $d->name . "\n" ?>
    address                 <?= $d->mgmt_host . "\n" ?>
    _apiurl                 <?= $d->api . "\n" ?>
}

define service {
    use                     <?= $t->service_definition . "\n" ?>
    host_name               bird-<?= $d->handle . "\n" ?>
    check_command           <?= $checkCmd ?>!$_HOSTAPIURL$
}

<?php endforeach; ?>

<?php asort( $hosts ); ?>

define hostgroup {
    hostgroup_name          <?= $hg_name . "\n" ?>
    alias                   Individual Bird Daemons
    members                 <?= $t->softwrap( $hosts, 1, ', ', ', \\', 28 ) . "\n" ?>
}


### END ###
